# -*- coding: utf-8 -*-

desc 'Create ubuntu box'
task :create do
  sh 'bundle install --path=vendor/bundler'
  sh 'bundle exec vagrant basebox build \'ubuntu-12.10\''
  sh 'bundle exec vagrant basebox export \'ubuntu-12.10\''
  sh 'bundle exec vagrant box add \'ubuntu-12.10\' \'ubuntu-12.10.box\''
end
